language: php
php:
  - 5.5
  - 5.6
  - 7.1
  - hhvm

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES=beta

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

before_script:
  - composer install

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    - mike.vanriel@naenius.com
