name: PHPUnit Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.3'

            - name: Install dependencies
              run: composer install --no-progress --no-suggest --no-interaction

            - name: Run PHPUnit
              run: vendor/bin/phpunit
